import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,

  // ── New v2 tables ───────────────────────────────────────────────────────────

  userProfile: defineTable({
    userId: v.id("users"),
    role: v.union(v.literal("freelancer"), v.literal("marketer"), v.literal("builder")),
    // Freelancer
    whatTheySell:       v.optional(v.string()),
    targetCustomer:     v.optional(v.string()),
    painSignals:        v.optional(v.string()),
    proof:              v.optional(v.string()),
    // Marketer
    marketingSpecialty: v.optional(v.string()),
    channels:           v.optional(v.string()),
    companyTypes:       v.optional(v.string()),
    companySize:        v.optional(v.string()),
    revenueRange:       v.optional(v.string()),
    growthProblem:      v.optional(v.string()),
    clientBottleneck:   v.optional(v.string()),
    metricsImproved:    v.optional(v.string()),
    bestResult:         v.optional(v.string()),
    // Builder
    productUrl:         v.optional(v.string()),
    productName:        v.optional(v.string()),
    productTagline:     v.optional(v.string()),
    productDescription: v.optional(v.string()),
    productTags:        v.optional(v.array(v.string())),
    revenueModel:       v.optional(v.union(v.literal("free"), v.literal("freemium"), v.literal("paid"))),
    stage:              v.optional(v.union(v.literal("idea"), v.literal("mvp"), v.literal("growth"))),
    userCount:          v.optional(v.string()),
    revenue:            v.optional(v.string()),
    // ICP (generated by LLM for builders, stored here)
    icpWhoBluefit:      v.optional(v.string()),
    icpRole:            v.optional(v.string()),
    icpPainPoints:      v.optional(v.string()),
    icpSwitchTrigger:   v.optional(v.string()),
    // Completion gate — absent = onboarding not done
    completedAt:        v.optional(v.number()),
  }).index("by_user", ["userId"]),

  userQueries: defineTable({
    userId:       v.id("users"),
    subreddits:   v.array(v.string()),  // 10 max, no r/ prefix
    queries:      v.array(v.string()),  // 5 max, each ≤80 chars
    generatedAt:  v.number(),
    lastFetchAt:  v.optional(v.number()),
  }).index("by_user", ["userId"]),

  feedPosts: defineTable({
    userId:         v.id("users"),
    postId:         v.string(),
    title:          v.string(),
    body:           v.string(),
    author:         v.string(),
    subreddit:      v.string(),
    url:            v.string(),
    ups:            v.number(),
    numComments:    v.number(),
    createdUtc:     v.number(),
    fetchedAt:      v.number(),
    matchedQueries: v.array(v.string()),
  })
    .index("by_user",         ["userId"])
    .index("by_user_post",    ["userId", "postId"])
    .index("by_user_fetched", ["userId", "fetchedAt"])
    .index("by_user_created", ["userId", "createdUtc"]),

  // ── Unchanged tables ────────────────────────────────────────────────────────

  agentTokens: defineTable({
    userId:           v.id("users"),
    token:            v.string(),
    telegramChatId:   v.optional(v.string()),
    telegramUsername: v.optional(v.string()),
    discordUserId:    v.optional(v.string()),
    discordChannelId: v.optional(v.string()),
    discordUsername:  v.optional(v.string()),
    paused:           v.optional(v.boolean()),
  })
    .index("by_user",    ["userId"])
    .index("by_token",   ["token"])
    .index("by_chat",    ["telegramChatId"])
    .index("by_discord", ["discordUserId"]),

  userDevices: defineTable({
    userId:       v.id("users"),
    ip:           v.string(),
    userAgent:    v.string(),
    registeredAt: v.number(),
    lastSeenAt:   v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_ip",   ["ip"]),

  alertedPosts: defineTable({
    userId:    v.id("users"),
    postId:    v.string(),
    platform:  v.optional(v.string()),
    alertedAt: v.number(),
  })
    .index("by_user_post",             ["userId", "postId"])
    .index("by_user_post_platform",    ["userId", "postId", "platform"])
    .index("by_user_platform_alerted", ["userId", "platform", "alertedAt"]),

  karmaCache: defineTable({
    author:    v.string(),
    karma:     v.number(),
    fetchedAt: v.number(),
  }).index("by_author", ["author"]),

  userVerification: defineTable({
    userId:     v.id("users"),
    verified:   v.boolean(),
    verifiedAt: v.optional(v.number()),
  }).index("by_user", ["userId"]),

  emailVerificationTokens: defineTable({
    userId:    v.id("users"),
    token:     v.string(),
    expiresAt: v.number(),
  })
    .index("by_token", ["token"])
    .index("by_user",  ["userId"]),

  proxyHealth: defineTable({
    timestamp:  v.number(),
    type:       v.string(),
    subreddits: v.string(),
    message:    v.string(),
  }).index("by_timestamp", ["timestamp"]),
});
