import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#df849d",
        "on-primary-container": "#611e35",
        "surface-container-low": "#f9f3eb",
        "on-primary-fixed-variant": "#762e45",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary": "#695d49",
        "secondary-fixed": "#e5e2e1",
        "on-surface": "#1d1b17",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#f2e0c8",
        "inverse-surface": "#32302b",
        "on-primary-fixed": "#3e021a",
        "surface": "#fff8f0",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#93455d",
        "on-tertiary-fixed": "#231a0b",
        "surface-container-high": "#ede7e0",
        "outline-variant": "#d8c1c5",
        "primary-fixed-dim": "#ffb1c4",
        "surface-container": "#f3ede5",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ac9d87",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f6f0e8",
        "tertiary-fixed-dim": "#d5c4ad",
        "inverse-primary": "#ffb1c4",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary-container": "#3f3524",
        "primary": "#93455d",
        "surface-variant": "#e7e2da",
        "on-secondary-fixed-variant": "#474646",
        "background": "#fff8f0",
        "primary-fixed": "#ffd9e1",
        "surface-container-highest": "#e7e2da",
        "on-secondary-container": "#656464",
        "surface-bright": "#fff8f0",
        "on-tertiary-fixed-variant": "#504533",
        "on-error-container": "#93000a",
        "outline": "#857276",
        "surface-dim": "#dfd9d2",
        "secondary-container": "#e5e2e1",
        "secondary": "#5f5e5e",
        "error-container": "#ffdad6",
        "on-surface-variant": "#534346",
        "on-background": "#1d1b17",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        serif: ["Roboto Slab", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
