// Popular subreddits for autocomplete — filtered client-side, no API needed
export const POPULAR_SUBREDDITS = [
  // Tech & SaaS
  "saas","startups","entrepreneur","smallbusiness","business","marketing",
  "growthhacking","growth_hacking","digitalmarketing","SEO","webdev","programming",
  "learnprogramming","javascript","typescript","reactjs","nextjs","nodejs","python",
  "rust","golang","devops","aws","googlecloud","azure","docker","kubernetes",
  "opensource","github","softwaredevelopment","software","compsci","coding",
  "ProductManagement","product_management","agile","scrum","UXDesign","UI_Design",
  "userexperience","webdesign","graphic_design","frontend","backend","fullstack",
  "machinelearning","artificial","ChatGPT","OpenAI","LocalLLaMA","AIAssistants",
  "deeplearning","datascience","datasets","analytics","businessintelligence",
  "automation","nocode","lowcode","zapier","productivity","remotework","freelance",
  "forhire","hiring","cscareerquestions","ExperiencedDevs","sysadmin","netsec",
  "cybersecurity","hacking","netsecstudents","bugbounty","malware","privacy",
  "selfhosted","homelab","linuxadmin","linux","Ubuntu","MacOS","Windows11",
  "apple","google","microsoft","meta","Amazon","Netflix","Spotify","Slack",
  "notion","obsidian","airtable","salesforce","hubspot","shopify","wordpress",
  "webhosting","domainnames","ecommerce","dropshipping","affiliatemarketing",
  "passive_income","personalfinance","investing","stocks","cryptocurrency","bitcoin",
  "ethereum","defi","web3","nft","blockchain","fintech","venturecapital","ycombinator",
  // Communities
  "AskReddit","worldnews","news","politics","science","space","technology","Futurology",
  "IAmA","explainlikeimfive","todayilearned","interestingasfuck","mildlyinteresting",
  "Showerthoughts","unpopularopinion","changemyview","LifeProTips","YouShouldKnow",
  "HowTo","DIY","howdidIgethere","self","CasualConversation","socialskills",
  "relationship_advice","dating","Marriage","Parenting","family","mentalhealth",
  "depression","anxiety","therapy","meditation","yoga","fitness","loseit","gainit",
  "nutrition","HealthyFood","recipes","Cooking","MealPrepSunday","veganrecipes",
  "keto","intermittentfasting","running","bodyweightfitness","crossfit","nba","nfl",
  "soccer","formula1","tennis","golf","gaming","pcgaming","PS5","XboxSeriesX",
  "Nintendo","Steam","GameDeals","indiegaming","gamedev","unity3d","unrealengine",
  "movies","television","anime","books","writing","scifi","Fantasy","horror",
  "Music","WeAreTheMusicMakers","edmproduction","hiphopheads","indieheads",
  "photography","itookapicture","photocritique","travel","solotravel","backpacking",
  "digitalnomad","legaladvice","personalfinancecanada","UKPersonalFinance","ausfinance",
  "india","europe","canada","australia","unitedkingdom","de","france","brasil",
  // Popular defaults
  "funny","pics","gifs","videos","WTF","mildlyinfuriating","tifu","confession",
  "AmItheAsshole","AITA","offmychest","TrueOffMyChest","confession","povertyfinance",
  "antiwork","careerguidance","jobs","resumes","interviews","college","teenagers",
  "askteenagers","over30","over50","AskMen","AskWomen","TwoXChromosomes","malelivingspace",
].sort();
